"""initial_schema

Revision ID: ec71aaa3381a
Revises:
Create Date: 2026-07-26 07:06:20.832930
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec71aaa3381a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("causation_id", sa.String(length=128), nullable=True),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("subject_type", sa.String(length=64), nullable=True),
        sa.Column("subject_id", sa.String(length=160), nullable=True),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("input_digest", sa.String(length=80), nullable=True),
        sa.Column("output_digest", sa.String(length=80), nullable=True),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("payload_truncated", sa.Boolean(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("event_id", name="uq_audit_events_event_id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index("ix_audit_events_correlation", ["correlation_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index("ix_audit_events_occurred_at", ["occurred_at"], unique=False)
        batch_op.create_index(
            "ix_audit_events_subject", ["subject_type", "subject_id"], unique=False
        )

    op.create_table(
        "cancel_commands",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("cancel_id", sa.String(length=160), nullable=False),
        sa.Column("proposal_id", sa.String(length=160), nullable=False),
        sa.Column("broker_order_id", sa.String(length=128), nullable=False),
        sa.Column("order_hash", sa.String(length=71), nullable=False),
        sa.Column("account_scope", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cancel_commands")),
        sa.UniqueConstraint("cancel_id", name="uq_cancel_commands_cancel_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_cancel_commands_idempotency_key"),
    )
    with op.batch_alter_table("cancel_commands", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cancel_commands_broker_order_id"), ["broker_order_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cancel_commands_proposal_id"), ["proposal_id"], unique=False
        )

    op.create_table(
        "operator_actions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("action_id", sa.String(length=160), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("acted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operator_actions")),
        sa.UniqueConstraint("action_id", name="uq_operator_actions_action_id"),
        sa.UniqueConstraint("idempotency_key", name="uq_operator_actions_idempotency_key"),
    )
    with op.batch_alter_table("operator_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_operator_actions_action_type"), ["action_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_operator_actions_correlation_id"), ["correlation_id"], unique=False
        )

    op.create_table(
        "order_proposals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("proposal_id", sa.String(length=160), nullable=False),
        sa.Column("signal_id", sa.String(length=160), nullable=False),
        sa.Column("candidate_id", sa.String(length=160), nullable=True),
        sa.Column("risk_decision_id", sa.String(length=160), nullable=False),
        sa.Column("account_scope", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", sa.String(length=64), nullable=False),
        sa.Column("limit_price", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.String(length=32), nullable=False),
        sa.Column("order_hash", sa.String(length=71), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("proposal_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_proposals")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_order_proposals_idempotency_key")),
        sa.UniqueConstraint("order_hash", name="uq_order_proposals_order_hash"),
        sa.UniqueConstraint("proposal_id", name="uq_order_proposals_proposal_id"),
    )
    with op.batch_alter_table("order_proposals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_order_proposals_account_scope"), ["account_scope"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_proposals_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_proposals_risk_decision_id"), ["risk_decision_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_order_proposals_signal_id"), ["signal_id"], unique=False
        )
        batch_op.create_index(
            "ix_order_proposals_status_expires", ["status", "expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_order_proposals_symbol"), ["symbol"], unique=False)

    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.String(length=160), nullable=False),
        sa.Column("account_scope", sa.String(length=32), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cash", sa.String(length=64), nullable=False),
        sa.Column("buying_power", sa.String(length=64), nullable=False),
        sa.Column("equity", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
        sa.UniqueConstraint("snapshot_id", name="uq_portfolio_snapshots_snapshot_id"),
    )
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_portfolio_snapshots_scope_as_of", ["account_scope", "as_of"], unique=False
        )

    op.create_table(
        "research_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_runs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_research_runs_run_id")),
    )
    with op.batch_alter_table("research_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_runs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_research_runs_symbol"), ["symbol"], unique=False)

    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("risk_decision_id", sa.String(length=160), nullable=False),
        sa.Column("candidate_id", sa.String(length=160), nullable=True),
        sa.Column("proposal_id", sa.String(length=160), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rule_set_version", sa.String(length=64), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
        sa.UniqueConstraint("risk_decision_id", name="uq_risk_decisions_risk_decision_id"),
    )
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_risk_decisions_candidate_id"), ["candidate_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_risk_decisions_outcome"), ["outcome"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_risk_decisions_proposal_id"), ["proposal_id"], unique=False
        )

    op.create_table(
        "strategy_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("research_id", sa.String(length=160), nullable=True),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_runs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_strategy_runs_run_id")),
    )
    with op.batch_alter_table("strategy_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_strategy_runs_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_strategy_runs_research_id"), ["research_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_strategy_runs_strategy"), ["strategy"], unique=False)
        batch_op.create_index(batch_op.f("ix_strategy_runs_symbol"), ["symbol"], unique=False)

    op.create_table(
        "approval_challenges",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("challenge_id", sa.String(length=160), nullable=False),
        sa.Column("proposal_id", sa.String(length=160), nullable=False),
        sa.Column("order_hash", sa.String(length=71), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("challenge_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["order_proposals.proposal_id"],
            name=op.f("fk_approval_challenges_proposal_id_order_proposals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_challenges")),
        sa.UniqueConstraint("challenge_id", name="uq_approval_challenges_challenge_id"),
        sa.UniqueConstraint("token_hash", name="uq_approval_challenges_token_hash"),
    )
    with op.batch_alter_table("approval_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_challenges_order_hash"), ["order_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_approval_challenges_proposal_id"), ["proposal_id"], unique=False
        )
        batch_op.create_index(
            "ix_approval_challenges_status_expires", ["status", "expires_at"], unique=False
        )

    op.create_table(
        "broker_orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("broker_order_id", sa.String(length=128), nullable=False),
        sa.Column("client_order_id", sa.String(length=128), nullable=False),
        sa.Column("proposal_id", sa.String(length=160), nullable=False),
        sa.Column("order_hash", sa.String(length=71), nullable=False),
        sa.Column("account_scope", sa.String(length=32), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("broker_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["order_proposals.proposal_id"],
            name=op.f("fk_broker_orders_proposal_id_order_proposals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_orders")),
        sa.UniqueConstraint("broker_order_id", name="uq_broker_orders_broker_order_id"),
        sa.UniqueConstraint("client_order_id", name="uq_broker_orders_client_order_id"),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_broker_orders_idempotency_key")),
    )
    with op.batch_alter_table("broker_orders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_orders_proposal_id"), ["proposal_id"], unique=False
        )
        batch_op.create_index(
            "ix_broker_orders_proposal_status", ["proposal_id", "status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_broker_orders_status"), ["status"], unique=False)

    op.create_table(
        "research_packets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("research_id", sa.String(length=160), nullable=False),
        sa.Column("run_id", sa.String(length=160), nullable=True),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["research_runs.run_id"],
            name=op.f("fk_research_packets_run_id_research_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_packets")),
        sa.UniqueConstraint("research_id", name="uq_research_packets_research_id"),
    )
    with op.batch_alter_table("research_packets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_research_packets_as_of"), ["as_of"], unique=False)
        batch_op.create_index(batch_op.f("ix_research_packets_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_research_packets_symbol"), ["symbol"], unique=False)

    op.create_table(
        "trade_signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.String(length=160), nullable=False),
        sa.Column("research_id", sa.String(length=160), nullable=False),
        sa.Column("strategy_run_id", sa.String(length=160), nullable=True),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("strategy_version", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=10), nullable=False),
        sa.Column("intent", sa.String(length=16), nullable=False),
        sa.Column("strength", sa.String(length=64), nullable=False),
        sa.Column("target_weight", sa.String(length=64), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["strategy_run_id"],
            ["strategy_runs.run_id"],
            name=op.f("fk_trade_signals_strategy_run_id_strategy_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_signals")),
        sa.UniqueConstraint("signal_id", name="uq_trade_signals_signal_id"),
    )
    with op.batch_alter_table("trade_signals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trade_signals_research_id"), ["research_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trade_signals_strategy"), ["strategy"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_trade_signals_strategy_run_id"), ["strategy_run_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trade_signals_symbol"), ["symbol"], unique=False)

    op.create_table(
        "approval_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=160), nullable=False),
        sa.Column("challenge_id", sa.String(length=160), nullable=False),
        sa.Column("proposal_id", sa.String(length=160), nullable=False),
        sa.Column("order_hash", sa.String(length=71), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approver_identity", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["approval_challenges.challenge_id"],
            name=op.f("fk_approval_events_challenge_id_approval_challenges"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["order_proposals.proposal_id"],
            name=op.f("fk_approval_events_proposal_id_order_proposals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_events")),
        sa.UniqueConstraint("challenge_id", "outcome", name="uq_approval_events_challenge_outcome"),
        sa.UniqueConstraint("event_id", name="uq_approval_events_event_id"),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_approval_events_idempotency_key")),
    )
    with op.batch_alter_table("approval_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_events_challenge_id"), ["challenge_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_approval_events_proposal_id"), ["proposal_id"], unique=False
        )

    op.create_table(
        "broker_fills",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fill_id", sa.String(length=128), nullable=False),
        sa.Column("broker_order_id", sa.String(length=128), nullable=False),
        sa.Column("quantity", sa.String(length=64), nullable=False),
        sa.Column("price", sa.String(length=64), nullable=False),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("schema_version", sa.String(length=16), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=True),
        sa.Column("config_version", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_order_id"],
            ["broker_orders.broker_order_id"],
            name=op.f("fk_broker_fills_broker_order_id_broker_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_fills")),
        sa.UniqueConstraint("fill_id", name="uq_broker_fills_fill_id"),
    )
    with op.batch_alter_table("broker_fills", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_broker_fills_broker_order_id"), ["broker_order_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("broker_fills", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_fills_broker_order_id"))

    op.drop_table("broker_fills")
    with op.batch_alter_table("approval_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_events_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_approval_events_challenge_id"))

    op.drop_table("approval_events")
    with op.batch_alter_table("trade_signals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trade_signals_symbol"))
        batch_op.drop_index(batch_op.f("ix_trade_signals_strategy_run_id"))
        batch_op.drop_index(batch_op.f("ix_trade_signals_strategy"))
        batch_op.drop_index(batch_op.f("ix_trade_signals_research_id"))

    op.drop_table("trade_signals")
    with op.batch_alter_table("research_packets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_packets_symbol"))
        batch_op.drop_index(batch_op.f("ix_research_packets_run_id"))
        batch_op.drop_index(batch_op.f("ix_research_packets_as_of"))

    op.drop_table("research_packets")
    with op.batch_alter_table("broker_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_orders_status"))
        batch_op.drop_index("ix_broker_orders_proposal_status")
        batch_op.drop_index(batch_op.f("ix_broker_orders_proposal_id"))

    op.drop_table("broker_orders")
    with op.batch_alter_table("approval_challenges", schema=None) as batch_op:
        batch_op.drop_index("ix_approval_challenges_status_expires")
        batch_op.drop_index(batch_op.f("ix_approval_challenges_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_approval_challenges_order_hash"))

    op.drop_table("approval_challenges")
    with op.batch_alter_table("strategy_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategy_runs_symbol"))
        batch_op.drop_index(batch_op.f("ix_strategy_runs_strategy"))
        batch_op.drop_index(batch_op.f("ix_strategy_runs_research_id"))
        batch_op.drop_index(batch_op.f("ix_strategy_runs_correlation_id"))

    op.drop_table("strategy_runs")
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_decisions_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_risk_decisions_outcome"))
        batch_op.drop_index(batch_op.f("ix_risk_decisions_candidate_id"))

    op.drop_table("risk_decisions")
    with op.batch_alter_table("research_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_runs_symbol"))
        batch_op.drop_index(batch_op.f("ix_research_runs_correlation_id"))

    op.drop_table("research_runs")
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_portfolio_snapshots_scope_as_of")

    op.drop_table("portfolio_snapshots")
    with op.batch_alter_table("order_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_proposals_symbol"))
        batch_op.drop_index("ix_order_proposals_status_expires")
        batch_op.drop_index(batch_op.f("ix_order_proposals_signal_id"))
        batch_op.drop_index(batch_op.f("ix_order_proposals_risk_decision_id"))
        batch_op.drop_index(batch_op.f("ix_order_proposals_candidate_id"))
        batch_op.drop_index(batch_op.f("ix_order_proposals_account_scope"))

    op.drop_table("order_proposals")
    with op.batch_alter_table("operator_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_operator_actions_correlation_id"))
        batch_op.drop_index(batch_op.f("ix_operator_actions_action_type"))

    op.drop_table("operator_actions")
    with op.batch_alter_table("cancel_commands", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cancel_commands_proposal_id"))
        batch_op.drop_index(batch_op.f("ix_cancel_commands_broker_order_id"))

    op.drop_table("cancel_commands")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_events_subject")
        batch_op.drop_index("ix_audit_events_occurred_at")
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index("ix_audit_events_correlation")

    op.drop_table("audit_events")
    # ### end Alembic commands ###
