"""Paper broker and Robinhood MCP write path.

Execution is the only package allowed to receive broker write-tool access.
Upstream research and strategy packages must not import this package.

P03-T13 exposes the domain broker port and error taxonomy. P02-T9 exposes the
order/cancel state machines. P03-T14 exposes the deterministic Paper Broker
and fill simulator.
"""

from ainvest.execution.broker import (
    FORBIDDEN_REPLACE_METHOD_NAMES,
    READ_METHOD_NAMES,
    WRITE_METHOD_NAMES,
    BrokerAuthError,
    BrokerError,
    BrokerInvalidOrderError,
    BrokerRateLimitError,
    BrokerReadPort,
    BrokerRejectedError,
    BrokerSubmitOutcome,
    BrokerSubmitRequest,
    BrokerSubmitResult,
    BrokerTimeoutError,
    BrokerUnknownOutcomeError,
    BrokerWritePort,
    assert_no_replace_operation,
    assert_read_port_has_no_write_methods,
    cancel_is_confirmed_rejection,
    cancel_is_unknown_outcome,
)
from ainvest.execution.paper import (
    PaperBroker,
    PaperClock,
    PaperCostModel,
    PaperMarketEvent,
    PaperRejectReason,
    as_read_port,
    as_write_port,
)
from ainvest.execution.state_machine import (
    CANCEL_EDGES,
    CANCEL_TERMINAL,
    ORDER_EDGES,
    ORDER_TERMINAL,
    AuditBackedStatePersistence,
    CancelCommandState,
    IllegalTransitionError,
    InMemoryStatePersistence,
    OrderLifecycleState,
    PersistenceError,
    StaleStateError,
    StatePersistencePort,
    TransitionResult,
    is_cancel_transition_allowed,
    is_order_transition_allowed,
    legal_cancel_targets,
    legal_order_targets,
    transition_cancel,
    transition_order,
)

__all__ = [
    "CANCEL_EDGES",
    "CANCEL_TERMINAL",
    "FORBIDDEN_REPLACE_METHOD_NAMES",
    "ORDER_EDGES",
    "ORDER_TERMINAL",
    "READ_METHOD_NAMES",
    "WRITE_METHOD_NAMES",
    "AuditBackedStatePersistence",
    "BrokerAuthError",
    "BrokerError",
    "BrokerInvalidOrderError",
    "BrokerRateLimitError",
    "BrokerReadPort",
    "BrokerRejectedError",
    "BrokerSubmitOutcome",
    "BrokerSubmitRequest",
    "BrokerSubmitResult",
    "BrokerTimeoutError",
    "BrokerUnknownOutcomeError",
    "BrokerWritePort",
    "CancelCommandState",
    "IllegalTransitionError",
    "InMemoryStatePersistence",
    "OrderLifecycleState",
    "PaperBroker",
    "PaperClock",
    "PaperCostModel",
    "PaperMarketEvent",
    "PaperRejectReason",
    "PersistenceError",
    "StaleStateError",
    "StatePersistencePort",
    "TransitionResult",
    "as_read_port",
    "as_write_port",
    "assert_no_replace_operation",
    "assert_read_port_has_no_write_methods",
    "cancel_is_confirmed_rejection",
    "cancel_is_unknown_outcome",
    "is_cancel_transition_allowed",
    "is_order_transition_allowed",
    "legal_cancel_targets",
    "legal_order_targets",
    "transition_cancel",
    "transition_order",
]
