"""Domain commands, events, and correlation IDs for workflow orchestration.

The workflow package defines stable internal command/event interfaces for
orchestrators, workers, and APIs (P02-T10). It begins with an in-process
dispatcher while preserving a port suitable for a durable queue or Temporal.

Import rules: this package may import ``ainvest.schemas`` and may use
``ainvest.audit.digests`` for canonical digests. It must not import ORM models,
broker write clients, or reverse-depend from lower boundary packages.
"""

from ainvest.workflow.commands import (
    COMMAND_TYPE_TO_MODEL,
    ActorId,
    ActorKind,
    CancelOrderCommand,
    CommandEnvelope,
    ConsumeApprovalCommand,
    CreateProposalCommand,
    EvaluateRiskCommand,
    EvaluateStrategyCommand,
    ExecuteOrderCommand,
    InputDigest,
    ManualReviewResolution,
    ReconcileCommand,
    RequestApprovalCommand,
    ResolveManualReviewCommand,
    SizePositionCommand,
    WorkflowCommand,
    allocate_command_id,
)
from ainvest.workflow.dispatcher import (
    BlindBrokerRetryError,
    CommandDispatcher,
    DuplicateCommandError,
    IdempotencyStore,
    InMemoryIdempotencyStore,
    InProcessCommandDispatcher,
    UnknownCommandHandlerError,
    command_digest,
    ensure_not_blind_broker_retry,
)
from ainvest.workflow.events import (
    COMMAND_TO_EVENT_TYPE,
    ApprovalConsumedEvent,
    ApprovalRequestedEvent,
    CommandOutcome,
    CommandRejectedEvent,
    EventEnvelope,
    EventType,
    ManualReviewResolvedEvent,
    OrderCancelledEvent,
    OrderExecutedEvent,
    PositionSizedEvent,
    ProposalCreatedEvent,
    ReconciledEvent,
    RiskEvaluatedEvent,
    StrategyEvaluatedEvent,
    WorkflowEvent,
    allocate_event_id,
)
from ainvest.workflow.ids import (
    CausationId,
    CommandId,
    CorrelationId,
    EventId,
    IdempotencyId,
    TimedTrace,
    TraceContext,
    continue_trace,
    new_command_id,
    new_correlation_id,
    new_event_id,
    new_idempotency_id,
    require_same_correlation,
    start_trace,
)
from ainvest.workflow.semantics import (
    COMMAND_RETRY_SEMANTICS,
    CommandType,
    RetrySemantics,
    allows_blind_retry,
    is_broker_write,
    retry_semantics_for,
)

__all__ = [
    "COMMAND_RETRY_SEMANTICS",
    "COMMAND_TO_EVENT_TYPE",
    "COMMAND_TYPE_TO_MODEL",
    "ActorId",
    "ActorKind",
    "ApprovalConsumedEvent",
    "ApprovalRequestedEvent",
    "BlindBrokerRetryError",
    "CancelOrderCommand",
    "CausationId",
    "CommandDispatcher",
    "CommandEnvelope",
    "CommandId",
    "CommandOutcome",
    "CommandRejectedEvent",
    "CommandType",
    "ConsumeApprovalCommand",
    "CorrelationId",
    "CreateProposalCommand",
    "DuplicateCommandError",
    "EvaluateRiskCommand",
    "EvaluateStrategyCommand",
    "EventEnvelope",
    "EventId",
    "EventType",
    "ExecuteOrderCommand",
    "IdempotencyId",
    "IdempotencyStore",
    "InMemoryIdempotencyStore",
    "InProcessCommandDispatcher",
    "InputDigest",
    "ManualReviewResolution",
    "ManualReviewResolvedEvent",
    "OrderCancelledEvent",
    "OrderExecutedEvent",
    "PositionSizedEvent",
    "ProposalCreatedEvent",
    "ReconcileCommand",
    "ReconciledEvent",
    "RequestApprovalCommand",
    "ResolveManualReviewCommand",
    "RetrySemantics",
    "RiskEvaluatedEvent",
    "SizePositionCommand",
    "StrategyEvaluatedEvent",
    "TimedTrace",
    "TraceContext",
    "UnknownCommandHandlerError",
    "WorkflowCommand",
    "WorkflowEvent",
    "allocate_command_id",
    "allocate_event_id",
    "allows_blind_retry",
    "command_digest",
    "continue_trace",
    "ensure_not_blind_broker_retry",
    "is_broker_write",
    "new_command_id",
    "new_correlation_id",
    "new_event_id",
    "new_idempotency_id",
    "require_same_correlation",
    "retry_semantics_for",
    "start_trace",
]
